use super::*;

pub static OPCODE_TABLE_PREFIXED: [Option<OpcodeInfo>; 256] = [
    // 0x00 - 0x0F
    S(OI::new(I::RLC(AS8::B), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::C), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::D), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::E), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::H), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::L), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::HLI), "X", 0, 16)),
    S(OI::new(I::RLC(AS8::A), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::B), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::C), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::D), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::E), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::H), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::L), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::HLI), "X", 0, 16)),
    S(OI::new(I::RRC(AS8::A), "X", 0, 8)),
    // 0x10 - 0x1F
    S(OI::new(I::RL(AS8::B), "X", 0, 8)),
    S(OI::new(I::RL(AS8::C), "X", 0, 8)),
    S(OI::new(I::RL(AS8::D), "X", 0, 8)),
    S(OI::new(I::RL(AS8::E), "X", 0, 8)),
    S(OI::new(I::RL(AS8::H), "X", 0, 8)),
    S(OI::new(I::RL(AS8::L), "X", 0, 8)),
    S(OI::new(I::RL(AS8::HLI), "X", 0, 16)),
    S(OI::new(I::RL(AS8::A), "X", 0, 8)),
    S(OI::new(I::RR(AS8::B), "X", 0, 8)),
    S(OI::new(I::RR(AS8::C), "X", 0, 8)),
    S(OI::new(I::RR(AS8::D), "X", 0, 8)),
    S(OI::new(I::RR(AS8::E), "X", 0, 8)),
    S(OI::new(I::RR(AS8::H), "X", 0, 8)),
    S(OI::new(I::RR(AS8::L), "X", 0, 8)),
    S(OI::new(I::RR(AS8::HLI), "X", 0, 16)),
    S(OI::new(I::RR(AS8::A), "X", 0, 8)),
    // 0x20 - 0x2F
    S(OI::new(I::SLA(AS8::B), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::C), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::D), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::E), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::H), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::L), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::HLI), "X", 0, 16)),
    S(OI::new(I::SLA(AS8::A), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::B), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::C), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::D), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::E), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::H), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::L), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::HLI), "X", 0, 16)),
    S(OI::new(I::SRA(AS8::A), "X", 0, 8)),
    // 0x30 - 0x3F
    S(OI::new(I::SWAP(AS8::B), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::C), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::D), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::E), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::H), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::L), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::HLI), "X", 0, 16)),
    S(OI::new(I::SWAP(AS8::A), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::B), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::C), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::D), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::E), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::H), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::L), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::HLI), "X", 0, 16)),
    S(OI::new(I::SRL(AS8::A), "X", 0, 8)),
    // 0x40 - 0x4F
    S(OI::new(I::BIT(0, AS8::B), "BIT 0, B", 0, 8)),
    S(OI::new(I::BIT(0, AS8::C), "BIT 0, C", 0, 8)),
    S(OI::new(I::BIT(0, AS8::D), "BIT 0, D", 0, 8)),
    S(OI::new(I::BIT(0, AS8::E), "BIT 0, E", 0, 8)),
    S(OI::new(I::BIT(0, AS8::H), "BIT 0, H", 0, 8)),
    S(OI::new(I::BIT(0, AS8::L), "BIT 0, L", 0, 8)),
    S(OI::new(I::BIT(0, AS8::HLI), "BIT 0, (HL)", 0, 12)),
    S(OI::new(I::BIT(0, AS8::A), "BIT 0, A", 0, 8)),
    S(OI::new(I::BIT(1, AS8::B), "BIT 1, B", 0, 8)),
    S(OI::new(I::BIT(1, AS8::C), "BIT 1, C", 0, 8)),
    S(OI::new(I::BIT(1, AS8::D), "BIT 1, D", 0, 8)),
    S(OI::new(I::BIT(1, AS8::E), "BIT 1, E", 0, 8)),
    S(OI::new(I::BIT(1, AS8::H), "BIT 1, H", 0, 8)),
    S(OI::new(I::BIT(1, AS8::L), "BIT 1, L", 0, 8)),
    S(OI::new(I::BIT(1, AS8::HLI), "BIT 1, (HL)", 0, 12)),
    S(OI::new(I::BIT(1, AS8::A), "BIT 1, A", 0, 8)),
    // 0x50 - 0x5F
    S(OI::new(I::BIT(2, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::HLI), "X", 0, 12)),
    S(OI::new(I::BIT(2, AS8::A), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::HLI), "X", 0, 12)),
    S(OI::new(I::BIT(3, AS8::A), "X", 0, 8)),
    // 0x60 - 0x6F
    S(OI::new(I::BIT(4, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::HLI), "X", 0, 12)),
    S(OI::new(I::BIT(4, AS8::A), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::HLI), "X", 0, 12)),
    S(OI::new(I::BIT(5, AS8::A), "X", 0, 8)),
    // 0x70 - 0x7F
    S(OI::new(I::BIT(6, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::HLI), "X", 0, 12)),
    S(OI::new(I::BIT(6, AS8::A), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::HLI), "X", 0, 12)),
    S(OI::new(I::BIT(7, AS8::A), "X", 0, 8)),
    // 0x80 - 0x8F
    S(OI::new(I::RES(0, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::HLI), "X", 0, 16)),
    S(OI::new(I::RES(0, AS8::A), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::HLI), "X", 0, 16)),
    S(OI::new(I::RES(1, AS8::A), "X", 0, 8)),
    // 0x90 - 0x9F
    S(OI::new(I::RES(2, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::HLI), "X", 0, 16)),
    S(OI::new(I::RES(2, AS8::A), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::HLI), "X", 0, 16)),
    S(OI::new(I::RES(3, AS8::A), "X", 0, 8)),
    // 0xA0 - 0xAF
    S(OI::new(I::RES(4, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::HLI), "X", 0, 16)),
    S(OI::new(I::RES(4, AS8::A), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::HLI), "X", 0, 16)),
    S(OI::new(I::RES(5, AS8::A), "X", 0, 8)),
    // 0xB0 - 0xBF
    S(OI::new(I::RES(6, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::HLI), "X", 0, 16)),
    S(OI::new(I::RES(6, AS8::A), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::HLI), "X", 0, 16)),
    S(OI::new(I::RES(7, AS8::A), "X", 0, 8)),
    // 0xC0 - 0xCF
    S(OI::new(I::SET(0, AS8::B), "SET 0, B", 2, 8)),
    S(OI::new(I::SET(0, AS8::C), "SET 0, C", 2, 8)),
    S(OI::new(I::SET(0, AS8::D), "SET 0, D", 2, 8)),
    S(OI::new(I::SET(0, AS8::E), "SET 0, E", 2, 8)),
    S(OI::new(I::SET(0, AS8::H), "SET 0, H", 2, 8)),
    S(OI::new(I::SET(0, AS8::L), "SET 0, L", 2, 8)),
    S(OI::new(I::SET(0, AS8::HLI), "SET 0, (HL)", 2, 16)),
    S(OI::new(I::SET(0, AS8::A), "SET 0, A", 2, 8)),
    S(OI::new(I::SET(1, AS8::B), "SET 1, B", 2, 8)),
    S(OI::new(I::SET(1, AS8::C), "SET 1, C", 2, 8)),
    S(OI::new(I::SET(1, AS8::D), "SET 1, D", 2, 8)),
    S(OI::new(I::SET(1, AS8::E), "SET 1, E", 2, 8)),
    S(OI::new(I::SET(1, AS8::H), "SET 1, H", 2, 8)),
    S(OI::new(I::SET(1, AS8::L), "SET 1, L", 2, 8)),
    S(OI::new(I::SET(1, AS8::HLI), "SET 1, (HL)", 2, 16)),
    S(OI::new(I::SET(1, AS8::A), "SET 1, A", 2, 8)),
    // 0xD0 - 0xDF
    S(OI::new(I::SET(2, AS8::B), "SET 2, B", 2, 8)),
    S(OI::new(I::SET(2, AS8::C), "SET 2, C", 2, 8)),
    S(OI::new(I::SET(2, AS8::D), "SET 2, D", 2, 8)),
    S(OI::new(I::SET(2, AS8::E), "SET 2, E", 2, 8)),
    S(OI::new(I::SET(2, AS8::H), "SET 2, H", 2, 8)),
    S(OI::new(I::SET(2, AS8::L), "SET 2, L", 2, 8)),
    S(OI::new(I::SET(2, AS8::HLI), "SET 2, (HL)", 2, 16)),
    S(OI::new(I::SET(2, AS8::A), "SET 2, A", 2, 8)),
    S(OI::new(I::SET(3, AS8::B), "SET 3, B", 2, 8)),
    S(OI::new(I::SET(3, AS8::C), "SET 3, C", 2, 8)),
    S(OI::new(I::SET(3, AS8::D), "SET 3, D", 2, 8)),
    S(OI::new(I::SET(3, AS8::E), "SET 3, E", 2, 8)),
    S(OI::new(I::SET(3, AS8::H), "SET 3, H", 2, 8)),
    S(OI::new(I::SET(3, AS8::L), "SET 3, L", 2, 8)),
    S(OI::new(I::SET(3, AS8::HLI), "SET 3, (HL)", 2, 16)),
    S(OI::new(I::SET(3, AS8::A), "SET 3, A", 2, 8)),
    // 0xE0 - 0xEF
    S(OI::new(I::SET(4, AS8::B), "SET 4, B", 2, 8)),
    S(OI::new(I::SET(4, AS8::C), "SET 4, C", 2, 8)),
    S(OI::new(I::SET(4, AS8::D), "SET 4, D", 2, 8)),
    S(OI::new(I::SET(4, AS8::E), "SET 4, E", 2, 8)),
    S(OI::new(I::SET(4, AS8::H), "SET 4, H", 2, 8)),
    S(OI::new(I::SET(4, AS8::L), "SET 4, L", 2, 8)),
    S(OI::new(I::SET(4, AS8::HLI), "SET 4, (HL)", 2, 16)),
    S(OI::new(I::SET(4, AS8::A), "SET 4, A", 2, 8)),
    S(OI::new(I::SET(5, AS8::B), "SET 5, B", 2, 8)),
    S(OI::new(I::SET(5, AS8::C), "SET 5, C", 2, 8)),
    S(OI::new(I::SET(5, AS8::D), "SET 5, D", 2, 8)),
    S(OI::new(I::SET(5, AS8::E), "SET 5, E", 2, 8)),
    S(OI::new(I::SET(5, AS8::H), "SET 5, H", 2, 8)),
    S(OI::new(I::SET(5, AS8::L), "SET 5, L", 2, 8)),
    S(OI::new(I::SET(5, AS8::HLI), "SET 5, (HL)", 2, 16)),
    S(OI::new(I::SET(5, AS8::A), "SET 5, A", 2, 8)),
    // 0xF0 - 0xFF
    S(OI::new(I::SET(6, AS8::B), "SET 6, B", 2, 8)),
    S(OI::new(I::SET(6, AS8::C), "SET 6, C", 2, 8)),
    S(OI::new(I::SET(6, AS8::D), "SET 6, D", 2, 8)),
    S(OI::new(I::SET(6, AS8::E), "SET 6, E", 2, 8)),
    S(OI::new(I::SET(6, AS8::H), "SET 6, H", 2, 8)),
    S(OI::new(I::SET(6, AS8::L), "SET 6, L", 2, 8)),
    S(OI::new(I::SET(6, AS8::HLI), "SET 6, (HL)", 2, 16)),
    S(OI::new(I::SET(6, AS8::A), "SET 6, A", 2, 8)),
    S(OI::new(I::SET(7, AS8::B), "SET 7, B", 2, 8)),
    S(OI::new(I::SET(7, AS8::C), "SET 7, C", 2, 8)),
    S(OI::new(I::SET(7, AS8::D), "SET 7, D", 2, 8)),
    S(OI::new(I::SET(7, AS8::E), "SET 7, E", 2, 8)),
    S(OI::new(I::SET(7, AS8::H), "SET 7, H", 2, 8)),
    S(OI::new(I::SET(7, AS8::L), "SET 7, L", 2, 8)),
    S(OI::new(I::SET(7, AS8::HLI), "SET 7, (HL)", 2, 16)),
    S(OI::new(I::SET(7, AS8::A), "SET 7, A", 2, 8)),
];