use super::*;

pub static OPCODE_TABLE_PREFIXED: [Option<OpcodeInfo>; 256] = [
    // 0x00 - 0x0F
    S(OI::new(I::RLC(AS8::B), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::C), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::D), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::E), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::H), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::L), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::HLI), "X", 0, 8)),
    S(OI::new(I::RLC(AS8::A), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::B), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::C), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::D), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::E), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::H), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::L), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::HLI), "X", 0, 8)),
    S(OI::new(I::RRC(AS8::A), "X", 0, 8)),
    // 0x10 - 0x1F
    S(OI::new(I::RL(AS8::B), "X", 0, 8)),
    S(OI::new(I::RL(AS8::C), "X", 0, 8)),
    S(OI::new(I::RL(AS8::D), "X", 0, 8)),
    S(OI::new(I::RL(AS8::E), "X", 0, 8)),
    S(OI::new(I::RL(AS8::H), "X", 0, 8)),
    S(OI::new(I::RL(AS8::L), "X", 0, 8)),
    S(OI::new(I::RL(AS8::HLI), "X", 0, 8)),
    S(OI::new(I::RL(AS8::A), "X", 0, 8)),
    S(OI::new(I::RR(AS8::B), "X", 0, 8)),
    S(OI::new(I::RR(AS8::C), "X", 0, 8)),
    S(OI::new(I::RR(AS8::D), "X", 0, 8)),
    S(OI::new(I::RR(AS8::E), "X", 0, 8)),
    S(OI::new(I::RR(AS8::H), "X", 0, 8)),
    S(OI::new(I::RR(AS8::L), "X", 0, 8)),
    S(OI::new(I::RR(AS8::HLI), "X", 0, 8)),
    S(OI::new(I::RR(AS8::A), "X", 0, 8)),
    // 0x20 - 0x2F
    S(OI::new(I::SLA(AS8::B), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::C), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::D), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::E), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::H), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::L), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::HLI), "X", 0, 8)),
    S(OI::new(I::SLA(AS8::A), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::B), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::C), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::D), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::E), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::H), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::L), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::HLI), "X", 0, 8)),
    S(OI::new(I::SRA(AS8::A), "X", 0, 8)),
    // 0x30 - 0x3F
    S(OI::new(I::SWAP(AS8::B), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::C), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::D), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::E), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::H), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::L), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::HLI), "X", 0, 8)),
    S(OI::new(I::SWAP(AS8::A), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::B), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::C), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::D), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::E), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::H), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::L), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::HLI), "X", 0, 8)),
    S(OI::new(I::SRL(AS8::A), "X", 0, 8)),
    // 0x40 - 0x4F
    S(OI::new(I::BIT(0, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(0, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(0, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(0, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(0, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(0, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(0, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::BIT(0, AS8::A), "X", 0, 8)),
    S(OI::new(I::BIT(1, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(1, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(1, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(1, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(1, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(1, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(1, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::BIT(1, AS8::A), "X", 0, 8)),
    // 0x50 - 0x5F
    S(OI::new(I::BIT(2, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::BIT(2, AS8::A), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::BIT(3, AS8::A), "X", 0, 8)),
    // 0x60 - 0x6F
    S(OI::new(I::BIT(4, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::BIT(4, AS8::A), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::BIT(5, AS8::A), "X", 0, 8)),
    // 0x70 - 0x7F
    S(OI::new(I::BIT(6, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::BIT(6, AS8::A), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::B), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::C), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::D), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::E), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::H), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::L), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::BIT(7, AS8::A), "X", 0, 8)),
    // 0x80 - 0x8F
    S(OI::new(I::RES(0, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::RES(0, AS8::A), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::RES(1, AS8::A), "X", 0, 8)),
    // 0x90 - 0x9F
    S(OI::new(I::RES(2, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::RES(2, AS8::A), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::RES(3, AS8::A), "X", 0, 8)),
    // 0xA0 - 0xAF
    S(OI::new(I::RES(4, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::RES(4, AS8::A), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::RES(5, AS8::A), "X", 0, 8)),
    // 0xB0 - 0xBF
    S(OI::new(I::RES(6, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::RES(6, AS8::A), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::B), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::C), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::D), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::E), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::H), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::L), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::HLI), "X", 0, 8)),
    S(OI::new(I::RES(7, AS8::A), "X", 0, 8)),
    // 0xC0 - 0xCF
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    // 0xD0 - 0xDF
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    // 0xE0 - 0xEF
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    // 0xF0 - 0xFF
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
];